### PR TITLE
Add accordions to free the DOM and load the icons faster + tooltip on icons

### PR DESCRIPTION
**Pull request by buenoC6**
### Fix issue about freeze with heavy list of icons + tooltip on icons

- This is a multiple accordions view.
- The ones with no results are hidden
- Add a feature to see the number of icons found from searchbar
- The DOM only loads visible icons

Capture d’écran 2023-11-03 à 23 59 53

Capture d’écran 2023-11-04 à 00 00 44

### CODE REVIEW

**Comment by buenoC6** [comment]
- Feature with accordions to display heavy list faster #11 
- Feature to add tooltip on hover #10

**Comment by DanielPantle** [comment]
@buenoC6 thanks a lot for your work, I really like the implementation! One thing prevents me from approving it yet: in my workflow I like to search for a icon and compare the icons from the different libraries to find the one that fits my needs the best. This is not as easy possible as before, because I have to expand all libraries to get an overview over all found icons.

Therefore I would suggest implementing a button to expand/collapse all accordeon groups, like this I think the best of both is combined :) do you think you can implement this? That would be really great!

**Comment by buenoC6** [comment]
@DanielPantle I appreciate your comment ! I just added the expand/collapse button. As you said, It's a nice feature in the search flow. It should combine now both vision :)

Here is a preview.

image

**Review by DanielPantle — APPROVED** [review]

**Comment by DanielPantle** [comment]
@buenoC6 thanks a lot again for your work and the fix with the "Expand" button, I really like it that way! :)

**Pull request merged**
